worker_processes auto;

http {
    # Sessions TLS (réduit les handshakes)
    ssl_session_cache   shared:SSL:10m;   # ~40k sessions
    ssl_session_timeout 10m;

    server {
        listen 443 ssl;
        server_name ameduboi.42.fr;

        ssl_certificate     /etc/nginx/ssl/ameduboi.42.fr.fullchain.crt;
        ssl_certificate_key /etc/nginx/ssl/ameduboi.42.fr.key;

        # Laisser ces valeurs par défaut est souvent OK sur versions récentes
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers   HIGH:!aNULL:!MD5;

        keepalive_timeout 70;

	location ~ \.php$ {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass wordpress:9000;
		fastcgi_index index.php;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param PATH_INFO $fastcgi_path_info;
	}
    }
}
